apiVersion: v1
kind: Service
metadata:
  name: itzg-mc-svc
spec:
  selector:
    app: itzg-mc-app
  ports:
    - protocol: "TCP"
      port: 25565
      targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 10.0.0.151
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itzg-mc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itzg-mc-app
  template:
    metadata:
      labels:
        app: itzg-mc-app
    spec:
      containers:
        - name: itzg-mc-node
          image: itzg/minecraft-server
          env:
          - name: EULA
            value: "TRUE"
          - name: VERSION
            value: "1.17.1"
          - name: TYPE
            value: "SPIGOT"
          - name: ONLINE_MODE
            value: "FALSE"
          volumeMounts:
              - name: mydata
                mountPath: "/data"
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: mc-app-volume