apiVersion: v1
kind: Service
metadata:
  name: main-mc-svc
spec:
  selector:
    app: main-mc-app
  ports:
    - protocol: "TCP"
      port: 25565
      targetPort: 25565
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-mc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-mc-app
  template:
    metadata:
      labels:
        app: main-mc-app
    spec:
      containers:
        - name: main-mc-node
          image: itzg/minecraft-server
          env:
          - name: EULA
            value: "TRUE"
          - name: VERSION
            value: "1.17.1"
          - name: TYPE
            value: "SPIGOT"
          - name: ONLINE_MODE
            value: "FALSE"
          volumeMounts:
              - name: mydata
                mountPath: "/data"
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: main-mc-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main-mc-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs