apiVersion: v1
kind: Service
metadata:
  name: mcserver-svc
spec:
  selector:
    app: mcserver-app
  ports:
    - protocol: "TCP"
      port: 25565
      targetPort: 25565
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcserver-app
  template:
    metadata:
      labels:
        app: mcserver-app
    spec:
      containers:
        - name: mcserver-node
          image: weakkajuma/minecraft-server:v1.17.1
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
        options:
          - name: ndots
            value: "2"
          - name: edns0